force-app/main/default/objects/Give_API_Token__mdt/Give_API_Token__mdt.object-meta.xml
<CustomObject>
    <description>Give API tokens used by custom integration to authenticate to the GiveWP API.</description>
    <label>Give API Token</label>
    <pluralLabel>Give API Tokens</pluralLabel>
</CustomObject>

force-app/main/default/objects/Give_API_Token__mdt/fields/Individual_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Individual_Account_ID__c</fullName>
    <label>Individual Account ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Give_API_Token__mdt/fields/Organizational_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Organizational_Account_ID__c</fullName>
    <label>Organizational Account ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/Membership_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps default values based on value received from giving system</description>
    <label>Membership Mapping</label>
    <pluralLabel>Membership Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Donation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Record_Type__c</fullName>
    <label>Donation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
                <default>true</default>
                <label>Membership</label>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Membership_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Sub_Type__c</fullName>
    <label>Membership Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
                <default>true</default>
                <label>Student</label>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Supporter</fullName>
            </value>
            <value>
                <fullName>Champion</fullName>
            </value>
            <value>
                <fullName>&lt; $250k</fullName>
            </value>
            <value>
                <fullName>$250k-$500k</fullName>
            </value>
            <value>
                <fullName>$500k - $1MM</fullName>
            </value>
            <value>
                <fullName>$1MM+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Arts Organization</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needs to Renew</fullName>
                <default>true</default>
                <label>Needs to Renew</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Donation Received – Acknowledgement Need</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
                <default>true</default>
                <label>Membership</label>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Pledge</fullName>
            </value>
            <value>
                <fullName>Major Gift</fullName>
            </value>
            <value>
                <fullName>Matching</fullName>
            </value>
            <value>
                <fullName>Enterprise - $2,500</fullName>
            </value>
            <value>
                <fullName>Corporate - $1,250</fullName>
            </value>
            <value>
                <fullName>Business - $500</fullName>
            </value>
            <value>
                <fullName>Small Business - $300</fullName>
            </value>
            <value>
                <fullName>Entrepreneur - $150</fullName>
            </value>
            <value>
                <fullName>Individual - $100</fullName>
            </value>
            <value>
                <fullName>Visionary - $50,000.00</fullName>
            </value>
            <value>
                <fullName>Lead Investor - $25,000.00</fullName>
            </value>
            <value>
                <fullName>Investor - $15,000.00</fullName>
            </value>
            <value>
                <fullName>Catalyst - $10,000.00</fullName>
            </value>
            <value>
                <fullName>Chairman&apos;s Circle - $7,500.00</fullName>
            </value>
            <value>
                <fullName>President&apos;s Circle - $5,000.00</fullName>
            </value>
            <value>
                <fullName>Executive Circle - $3,500.00</fullName>
            </value>
            <value>
                <fullName>Super Fan - $2,500.00</fullName>
            </value>
            <value>
                <fullName>Patron - $1,500.00</fullName>
            </value>
            <value>
                <fullName>Fan - $1,250.00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/User_Entered_Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Entered_Organization_Name__c</fullName>
    <description>Contains the value entered by the user on the website when making a donation</description>
    <label>User Entered Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DonationCreationService.cls
/**
 * Created by lydon.bergin on 10/30/20.
 */

public class DonationCreationService {
    @InvocableMethod(Label='Build Opportunities from Donations' Description='Given donations in, build opportunity records' Category='Custom')
    public static List<List<Opportunity>> buildOpportunities(List<List<Donation>> donations) {
        System.debug('Invoke build opportunities');
        List<Opportunity> opportunities = new List<Opportunity>();

        Map<String, Membership_Mapping__mdt> maps = MappingMetadataSelector.getMembershipMappingsByLabel();
        Map<String, Schema.RecordTypeInfo> recordTypesByName = Opportunity.SObjectType.getDescribe().getRecordTypeInfosByName();
        Give_API_Token__mdt giveMetadata = MappingMetadataSelector.getGiveApiMetadata();

        List<String> donationEmails = new List<String>();
        List<String> membershipEmails = new List<String>();
        List<String> allEmails = new List<String>();
        for (List<Donation> donationList : donations) {
            for (Donation donation : donationList) {
                allEmails.add(donation.email);
                if (donation.giveCurrentUrl.toUpperCase().contains('DONATIONS') || donation.giveCurrentUrl.toUpperCase().contains('DONATE')) {
                    donationEmails.add(donation.email);
                } else {
                    membershipEmails.add(donation.email);
                }
            }
        }
        Map<String, Opportunity> existingDonationOpps = OpportunitySelector.getExistingDonationOpportunities(donationEmails);
        Map<String, Opportunity> existingMembershipOpps = OpportunitySelector.getExistingMembershipOpportunities(membershipEmails);
        Map<String, Contact> existingIndividualContacts = ContactSelector.getExistingIndividualContactsByEmail(allEmails, giveMetadata.Individual_Account_ID__c);
        Map<String, Contact> existingOrganizationalContacts = ContactSelector.getExistingOrganizationalContactsByEmail(allEmails, giveMetadata.Individual_Account_ID__c);

        for (List<Donation> donationList : donations) {
            for (Donation donation : donationList) {
                Opportunity foundOpportunity;
                if ((donation.giveCurrentUrl.toUpperCase().contains('DONATIONS') || donation.giveCurrentUrl.toUpperCase().contains('DONATE')) && existingDonationOpps.containsKey(donation.email.toUpperCase())) {
                    foundOpportunity = existingDonationOpps.get(donation.email.toUpperCase());
                }
                else if (existingMembershipOpps.containsKey(donation.email.toUpperCase())) {
                    foundOpportunity = existingMembershipOpps.get(donation.email.toUpperCase());
                }
                else {
                    opportunities.add(
                            buildOpportunityFromDonation(
                                    donation,
                                    maps,
                                    recordTypesByName,
                                    foundOpportunity,
                                    existingIndividualContacts,
                                    existingOrganizationalContacts,
                                    giveMetadata.Individual_Account_ID__c,
                                    giveMetadata.Organizational_Account_Id__c
                            )
                    );
                }
            }
        }

        List<List<Opportunity>> returnList = new List<List<Opportunity>>();
        insert opportunities;
        returnList.add(opportunities);
        return returnList;
    }

    private static Opportunity buildOpportunityFromDonation(
            Donation donation,
            Map<String, Membership_Mapping__mdt> maps,
            Map<String, Schema.RecordTypeInfo> recordTypesByName,
            Opportunity foundOpportunity,
            Map<String, Contact> existingIndividualContacts,
            Map<String, Contact> existingOrganizationalContacts,
            Id individualAccountId,
            Id organizationalAccountId
    ) {
        Opportunity opportunity;
        if (foundOpportunity != null) {
            opportunity = foundOpportunity;
        }
        else {
            opportunity = new Opportunity();
        }

        Membership_Mapping__mdt currentMap;
        if (maps.containsKey(donation.formPriceName)) {
            currentMap = maps.get(donation.formPriceName);
        }
        else if (String.isNotBlank(donation.artsOrganizationIfApplicable)) {
            currentMap = maps.get('Donation: Organization');
        }
        else {
            currentMap = maps.get('Donation: Individual');
        }

        // Populate fields from metadata map
        opportunity.RecordTypeId = recordTypesByName.get(currentMap.Donation_Record_Type__c)?.recordTypeId;
        opportunity.Type = currentMap.Type__c;
        opportunity.Membership_Type__c = currentMap.Membership_Type__c;
        opportunity.Membership_SubType__c = currentMap.Membership_Sub_Type__c;
        opportunity.StageName = currentMap.Stage__c;
        opportunity.CampaignId = currentMap.Campaign__c;

        // Populate fields from donation
        opportunity.Give_ID__c = String.valueOf(donation.giveId);
        opportunity.CloseDate = donation.giveDate?.date();

        // Populate fields with logic rules
        opportunity.Amount = donation.donationAmount == null ? donation.totalAmount : donation.donationAmount;
        opportunity.Name = 'FY' + Date.today().year() + ' ' + currentMap.Type__c + ' ' + donation.name;
        if (donation.giveCurrentUrl.toUpperCase().contains('DONATIONS') || donation.giveCurrentUrl.toUpperCase().contains('DONATE')) {
            opportunity.Fiscally_Sponsored_Project_Name__c = donation.formName;
        }

        // Individual
        if (String.isBlank(donation.artsOrganizationIfApplicable)) {
            if (existingIndividualContacts.containsKey(donation.email.toUpperCase())) {
                opportunity.ContactId = existingIndividualContacts.get(donation.email.toUpperCase()).Id;
                opportunity.Primary_Contact__c = existingIndividualContacts.get(donation.email.toUpperCase()).Id;
                opportunity.AccountId = individualAccountId;
            }
            else if (existingOrganizationalContacts.containsKey(donation.email.toUpperCase())) {
                opportunity.StageName = 'Pending';
                opportunity.ContactId = existingOrganizationalContacts.get(donation.email.toUpperCase()).Id;
                opportunity.Primary_Contact__c = existingOrganizationalContacts.get(donation.email.toUpperCase()).Id;
                opportunity.AccountId = existingOrganizationalContacts.get(donation.email.toUpperCase()).AccountId;
            }
            else {
                Contact contact = generateContactFromDonation(donation, individualAccountId);
                // TODO: Bulkify
                insert contact;
                opportunity.ContactId = contact.Id;
                opportunity.AccountId = individualAccountId;
            }
        }

        // Organization
        else {
            opportunity.User_Entered_Organization_Name__c = donation.artsOrganizationIfApplicable;
            opportunity.StageName = 'Pending';
            if (existingOrganizationalContacts.containsKey(donation.email.toUpperCase())) {
                opportunity.ContactId = existingOrganizationalContacts.get(donation.email.toUpperCase()).Id;
                opportunity.Primary_Contact__c = existingOrganizationalContacts.get(donation.email.toUpperCase()).Id;
                opportunity.AccountId = existingOrganizationalContacts.get(donation.email.toUpperCase()).AccountId;
            }
            else if (existingIndividualContacts.containsKey(donation.email.toUpperCase())) {
                opportunity.StageName = 'Pending';
                opportunity.ContactId = existingIndividualContacts.get(donation.email.toUpperCase()).Id;
                opportunity.Primary_Contact__c = existingIndividualContacts.get(donation.email.toUpperCase()).Id;
                opportunity.AccountId = individualAccountId;
            }
            else {
                Contact contact = generateContactFromDonation(donation, organizationalAccountId);
                // TODO: Bulkify
                insert contact;
                opportunity.ContactId = contact.Id;
                opportunity.AccountId = organizationalAccountId;
            }
        }

        if(donation.isDonationRecurring) {
            opportunity.Recurring__c = 'Recurring';
        }

        return opportunity;
    }

    private static Contact generateContactFromDonation(Donation donation, Id accountId) {
        Contact contact = new Contact();
        contact.AccountId = accountId;
        contact.FirstName = donation.firstName;
        contact.LastName = donation.lastName;
        contact.Email = donation.email;
        contact.mailingStreet = donation.billingAddress1 + ' ' + donation.billingAddress2;
        contact.mailingCity = donation.billingCity;
        contact.MailingState = donation.billingState;
        contact.mailingPostalCode = donation.billingZip;
        contact.MailingCountry = donation.billingCountry;
        return contact;
    }
}