force-app/main/default/objects/Give_API_Token__mdt/Give_API_Token__mdt.object-meta.xml
<CustomObject>
    <description>Give API tokens used by custom integration to authenticate to the GiveWP API.</description>
    <label>Give API Token</label>
    <pluralLabel>Give API Tokens</pluralLabel>
</CustomObject>

force-app/main/default/objects/Give_API_Token__mdt/fields/Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Public_Key__c</fullName>
    <label>Public Key</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Give_API_Token__mdt/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GiveWPDonationLoader.cls
/**
 * Created by lydon.bergin on 12/9/20.
 */

public class GiveWPDonationLoader {
    @Future(callout=true)
    public static void loadGiveWPDonations(String dateParam, String numberParam) {
        Give_API_Token__mdt tokens = MappingMetadataSelector.getGiveApiMetadata();
        List<List<DonationParameter>> params = new List<List<DonationParameter>>();
        DonationParameter dp = new DonationParameter();
        dp.key = tokens.Public_Key__c;
        dp.token = tokens.Token__c;
        dp.dateParam = dateParam;
        dp.numberParam = numberParam;

        params.add(new List<DonationParameter>{dp});

        List<List<Donation>> donations = GiveWPDonationService.getDonations(params);
        List<List<Opportunity>> opps = DonationCreationService.buildOpportunities(donations);
    }
}