force-app/main/default/objects/Give_API_Token__mdt/Give_API_Token__mdt.object-meta.xml
<CustomObject>
    <description>Give API tokens used by custom integration to authenticate to the GiveWP API.</description>
    <label>Give API Token</label>
    <pluralLabel>Give API Tokens</pluralLabel>
</CustomObject>

force-app/main/default/objects/Give_API_Token__mdt/fields/Donation_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Donation_Prefix__c</fullName>
    <label>Donation Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Give_API_Token__mdt/fields/Individual_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Individual_Account_ID__c</fullName>
    <label>Individual Account ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Give_API_Token__mdt/fields/Organizational_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Organizational_Account_ID__c</fullName>
    <label>Organizational Account ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Give_API_Token__mdt/fields/Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Public_Key__c</fullName>
    <label>Public Key</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Give_API_Token__mdt/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/Membership_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps default values based on value received from giving system</description>
    <label>Membership Mapping</label>
    <pluralLabel>Membership Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Donation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Record_Type__c</fullName>
    <label>Donation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
                <default>true</default>
                <label>Membership</label>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Membership_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Sub_Type__c</fullName>
    <label>Membership Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
                <default>true</default>
                <label>Student</label>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Supporter</fullName>
            </value>
            <value>
                <fullName>Champion</fullName>
            </value>
            <value>
                <fullName>&lt; $250k</fullName>
            </value>
            <value>
                <fullName>$250k-$500k</fullName>
            </value>
            <value>
                <fullName>$500k - $1MM</fullName>
            </value>
            <value>
                <fullName>$1MM+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Arts Organization</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needs to Renew</fullName>
                <default>true</default>
                <label>Needs to Renew</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Donation Received – Acknowledgement Need</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
                <default>true</default>
                <label>Membership</label>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Pledge</fullName>
            </value>
            <value>
                <fullName>Major Gift</fullName>
            </value>
            <value>
                <fullName>Matching</fullName>
            </value>
            <value>
                <fullName>Enterprise - $2,500</fullName>
            </value>
            <value>
                <fullName>Corporate - $1,250</fullName>
            </value>
            <value>
                <fullName>Business - $500</fullName>
            </value>
            <value>
                <fullName>Small Business - $300</fullName>
            </value>
            <value>
                <fullName>Entrepreneur - $150</fullName>
            </value>
            <value>
                <fullName>Individual - $100</fullName>
            </value>
            <value>
                <fullName>Visionary - $50,000.00</fullName>
            </value>
            <value>
                <fullName>Lead Investor - $25,000.00</fullName>
            </value>
            <value>
                <fullName>Investor - $15,000.00</fullName>
            </value>
            <value>
                <fullName>Catalyst - $10,000.00</fullName>
            </value>
            <value>
                <fullName>Chairman&apos;s Circle - $7,500.00</fullName>
            </value>
            <value>
                <fullName>President&apos;s Circle - $5,000.00</fullName>
            </value>
            <value>
                <fullName>Executive Circle - $3,500.00</fullName>
            </value>
            <value>
                <fullName>Super Fan - $2,500.00</fullName>
            </value>
            <value>
                <fullName>Patron - $1,500.00</fullName>
            </value>
            <value>
                <fullName>Fan - $1,250.00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MappingMetadataSelector.cls
/**
 * Created by lydon.bergin on 10/30/20.
 */

public class MappingMetadataSelector {
    public static Map<String, Membership_Mapping__mdt> getMembershipMappingsByLabel() {
        List<Membership_Mapping__mdt> membershipMappings = [
            SELECT
                Campaign__c,
                DeveloperName,
                Donation_Record_Type__c,
                Id,
                Label,
                Language,
                MasterLabel,
                Membership_Sub_Type__c,
                Membership_Type__c,
                NamespacePrefix,
                QualifiedApiName,
                Stage__c,
                Type__c
            FROM Membership_Mapping__mdt
        ];

        Map<String, Membership_Mapping__mdt> membershipMappingsByLabel = new Map<String, Membership_Mapping__mdt>();
        for (Membership_Mapping__mdt mapping : membershipMappings) {
            membershipMappingsByLabel.put(mapping.Label, mapping);
        }

        return membershipMappingsByLabel;
    }

    public static Give_API_Token__mdt getGiveApiMetadata() {
        return [
                SELECT
                        DeveloperName,
                        Id,
                        Individual_Account_Id__c,
                        Organizational_Account_Id__c,
                        Donation_Prefix__c,
                        Label,
                        Language,
                        MasterLabel,
                        NamespacePrefix,
                        Public_Key__c,
                        QualifiedApiName,
                        Token__c
                FROM Give_API_Token__mdt][0];
    }
}